name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.0
    steps:
      - name: Log Node Version
        run: |
          node -v
          cat /etc/os-release